MyApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from MyApp import views
from django.contrib.auth.views import LoginView,LogoutView

app_name="MyApp"

urlpatterns = [
    path('', views.home, name="home"),
    path('home/', views.home, name="home"),
    path('afterlogin_view/', views.afterlogin_view, name="afterlogin_view"),
    path('home_book_appointment/', views.home_book_appointment, name="home_book_appointment"),
    path('logout/', LogoutView.as_view(template_name='MyApp/home.html'),name='logout'),


    path('patientlogin/', views.PatientLogin, name="patientlogin"),
    path('patientsignup/', views.PatientSignUp, name="patientsignup"),
    path('patient_dashboard/', views.patient_dashboard, name="patient_dashboard"),
    path('patient_book_appointment/', views.patient_book_appointment, name="patient_book_appointment"),
    path('patient_my_appointment/', views.patient_my_appointment, name="patient_my_appointment"),
    path('patient_invoice/', views.patient_invoice, name="patient_invoice"),
    path('wait_approval/', views.wait_approval, name="wait_approval"),


    path('doctorlogin/', views.DoctorLogin, name="doctorlogin"),
    path('doctorsignup/', views.DoctorSignUp, name="doctorsignup"),
    path('doctor_dashboard/', views.doctor_dashboard, name="doctor_dashboard"),
    path('doctor_wait_approval/', views.doctor_wait_approval, name="doctor_wait_approval"),
    path('doctor_patient/', views.doctor_patient, name="doctor_patient"),
    path('doctor_appointment/', views.doctor_appointment, name="doctor_appointment"),
    path('doctor_view_patient/', views.doctor_view_patient, name="doctor_view_patient"),
    path('doctor_view_discharged_patient/', views.doctor_view_discharged_patient, name="doctor_view_discharged_patient"),
    path('doctor_view_appointment/', views.doctor_view_appointment, name="doctor_view_appointment"),
    path('doctor_delete_appointment/', views.doctor_delete_appointment, name="doctor_delete_appointment"),


    path('adminlogin/', views.AdminLogin, name="adminlogin"),
    path('adminsignup/', views.AdminSignUp, name="adminsignup"),
    path('admin_dashboard/', views.admin_dashboard, name="admin_dashboard"),
    path('admin_patient/', views.admin_patient, name="admin_patient"),
    path('admin_patient_record/', views.admin_patient_record, name="admin_patient_record"),
    path('admin_admit_patient/', views.admin_admit_patient, name="admin_admit_patient"),
    path('admin_approve_patient/', views.admin_approve_patient,name="admin_approve_patient"),
    path('admin_discharge_patient/', views.admin_discharge_patient,name='admin_discharge_patient'),
    path('approve_patient/<int:pk>', views.approve_patient,name='approve_patient'),
    path('reject_patient/<int:pk>', views.reject_patient,name='reject_patient'),
    path('update_patient/<int:pk>', views.update_patient,name='update_patient'),
    path('delete_patient/<int:pk>', views.delete_patient,name='delete_patient'),
    path('discharge_patient/<int:pk>', views.discharge_patient,name='discharge_patient'),
    path('download_pdf/<int:pk>', views.download_pdf,name='download_pdf'),

    path('admin_doctor/', views.admin_doctor, name="admin_doctor"),
    path('admin_doctor_record/', views.admin_doctor_record,name="admin_doctor_record"),
    path('admin_add_doctor/', views.admin_add_doctor,name="admin_add_doctor"),
    path('admin_approve_doctor/', views.admin_approve_doctor,name="admin_approve_doctor"),
    path('admin_doctor_specialization/', views.admin_doctor_specialization,name="admin_doctor_specialization"),
    path('update_doctor/<int:pk>', views.update_doctor,name='update_doctor'),
    path('delete_doctor/<int:pk>', views.delete_doctor,name='delete_doctor'),
    path('approve_doctor/<int:pk>', views.approve_doctor,name='approve_doctor'),
    path('reject_doctor/<int:pk>', views.reject_doctor,name='reject_doctor'),

    path('admin_appointment/', views.admin_appointment, name="admin_appointment"),
    path('admin_view_appointment/', views.admin_view_appointment, name="admin_view_appointment"),
    path('admin_add_appointment/', views.admin_add_appointment, name="admin_add_appointment"),
    path('admin_approve_appointment/', views.admin_approve_appointment, name="admin_approve_appointment"),
    path('approve_appointment/<int:pk>', views.approve_appointment,name='approve_appointment'),
    path('reject_appointment/<int:pk>', views.reject_appointment,name='reject_appointment'),
    path('delete_appointment/<int:pk>', views.delete_appointment,name='delete_appointment'),
]

MyProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from MyApp import views

app_name="MyApp"

urlpatterns = [
    path('', include('MyApp.urls')),
    path('home/', include('MyApp.urls')),
    path('about/', include('MyApp.urls')),
    path('afterlogin_view/', include('MyApp.urls')),
    path('logout/', include('MyApp.urls')),


    path('patientlogin/', include('MyApp.urls')),
    path('patientsignup/', include('MyApp.urls')),
    path('patient_dashboard/', include('MyApp.urls')),
    path('patient_book_appointment/', include('MyApp.urls')),
    path('patient_my_appointment/', include('MyApp.urls')),
    path("patient_invoice/", include('MyApp.urls')),
    path("wait_approval/", include('MyApp.urls')),


    path('doctorlogin/', include('MyApp.urls')),
    path('doctorsignup/', include('MyApp.urls')),
    path('doctor_dashboard/', include('MyApp.urls')),
    path("doctor_wait_approval/", include('MyApp.urls')),
    path("doctor_patient/", include('MyApp.urls')),
    path("doctor_patient/", include('MyApp.urls')),
    path("doctor_appointment/", include('MyApp.urls')),
    path("doctor_view_patient/", include('MyApp.urls')),
    path("doctor_view_discharged_patient/", include('MyApp.urls')),
    path('doctor_view_appointment/', include('MyApp.urls')),
    path('doctor_delete_appointment/', include('MyApp.urls')),


    path('adminlogin/', include('MyApp.urls')),
    path('adminsignup/', include('MyApp.urls')),
    path('admin_dashboard/', include('MyApp.urls')),
    path('admin_patient/', include('MyApp.urls')),
    path('admin_patient_record/', include('MyApp.urls')),
    path('admin_admit_patient/', include('MyApp.urls')),
    path('admin_approve_patient/', include('MyApp.urls')),
    path('approve_patient/<int:pk>', include('MyApp.urls')),
    path('admin_discharge_patient/', include('MyApp.urls')),
    path('discharge_patient/', include('MyApp.urls')),
    path('admin_appointment/', include('MyApp.urls')),
    path('update_patient/<int:pk>', include('MyApp.urls')),
    path('delete_patient/', include('MyApp.urls')),
    path('download_pdf/<int:pk>', include('MyApp.urls')),

    path('admin_doctor/', include('MyApp.urls')),
    path('admin_doctor_record/', include('MyApp.urls')),
    path('admin_add_doctor/', include('MyApp.urls')),
    path('admin_approve_doctor/', include('MyApp.urls')),
    path('approve_doctor/<int:pk>', include('MyApp.urls')),
    path('reject_doctor/<int:pk>', include('MyApp.urls')),
    path('admin_doctor_specialization/', include('MyApp.urls')),
    path('update_doctor/<int:pk>', include('MyApp.urls')),
    path('delete_doctor/', include('MyApp.urls')),

    path('admin_appointment/', include('MyApp.urls')),
    path('admin_view_appointment/', include('MyApp.urls')),
    path('admin_add_appointment/', include('MyApp.urls')),
    path('admin_approve_appointment/', include('MyApp.urls')),
    path('approve_appointment/<int:pk>',include('MyApp.urls')),
    path('reject_appointment/<int:pk>', include('MyApp.urls')),
    path('delete_appointment/<int:pk>', include('MyApp.urls')),

    path('admin/', admin.site.urls),
]

MyApp/views.py
from django.shortcuts import render, redirect
from MyApp.forms import PatientUserInfo, PatientSignUpForm, DoctorUserInfo, DoctorSignUpForm, AdminUserInfo, AdminSignUpForm, PatientAppointmentForm
from MyApp.models import Patient, Doctor, Appointment, PatientDischarge

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from datetime import date



#-------------------------------- MAIN PAGE VIEWS ----------------------------------
#-----------------------------------------------------------------------------------

def home(request):
    return render(request, 'MyApp/home.html')

def home_book_appointment(request):
    return render(request, 'MyApp/home_book_appointment.html')

def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()
def is_doctor(user):
    return user.groups.filter(name='DOCTOR').exists()
def is_patient(user):
    return user.groups.filter(name='PATIENT').exists()
#---------AFTER ENTERING CREDENTIALS WE CHECK WHETHER USERNAME AND PASSWORD IS OF ADMIN,DOCTOR OR PATIENT
def afterlogin_view(request):
    if is_admin(request.user):
        return redirect('MyApp:admin_dashboard')
    elif is_doctor(request.user):
        accountapproval=Doctor.objects.all().filter(user_id=request.user.id,status=True)
        if accountapproval:
            return redirect('MyApp:doctor_dashboard')
        else:
            return render(request,'MyApp/wait_approval.html')
    elif is_patient(request.user):
        accountapproval=Patient.objects.all().filter(user_id=request.user.id,status=True)
        if accountapproval:
            return redirect('MyApp:patient_dashboard')
        else:
            return render(request,'MyApp/wait_approval.html')

#------------------------ PATIENT RELATED VIEWS START ------------------------------
#-----------------------------------------------------------------------------------

@login_required
def patient_dashboard(request):
    appointments=Appointment.objects.all().filter(patientId=request.user.id).order_by('-id')[:1]
    appointment=Appointment.objects.all().filter(patientId=request.user.id).count()
    print(appointment)
    if appointment!=0:
        status=appointments[0].status
        if status==True:
            doctorID=appointments[0].get_docId
            doctors=Doctor.objects.all().get(user_id=doctorID)
            mydict={
            'doctorName':appointments[0].doctorName,
            'doctorcontact':doctors.contact,
            'symptoms':appointments[0].description,
            'admitDate':appointments[0].appointmentDate,
            }
    else:
        print("hey")
        mydict={
        'doctorName':"Not assigned",
        'doctorcontact':"Not assigned",
        'symptoms':"Not assigned",
        'admitDate':"Not assigned",
        }
    return render (request, 'MyApp/patient_dashboard.html',context=mydict)

@login_required
def patient_invoice(request):
    patient=Patient.objects.get(user_id=request.user.id) #for profile picture of patient in sidebar
    dischargeDetails=PatientDischarge.objects.all().filter(patientId=patient.id).order_by('-id')[:1]
    patientDict=None
    if dischargeDetails:
        patientDict ={
        'is_discharged':True,
        'patient':patient,
        'patientId':patient.id,
        'patientName':patient.get_name,
        'assignedDoctorName':dischargeDetails[0].assignedDoctorName,
        'address':patient.address,
        'mobile':patient.contact,
        'symptoms':patient.symptoms,
        'admitDate':patient.admitDate,
        'releaseDate':dischargeDetails[0].releaseDate,
        'daySpent':dischargeDetails[0].daySpent,
        'medicineCost':dischargeDetails[0].medicineCost,
        'roomCharge':dischargeDetails[0].roomCharge,
        'doctorFee':dischargeDetails[0].doctorFee,
        'OtherCharge':dischargeDetails[0].OtherCharge,
        'total':dischargeDetails[0].total,
        }
        print(patientDict)
    else:
        patientDict={
            'is_discharged':False,
            'patient':patient,
            'patientId':request.user.id,
        }
    return render(request,'MyApp/Patient_Invoice.html',context=patientDict)

@login_required
def patient_book_appointment(request):
    appointmentForm=PatientAppointmentForm()
    patient=Patient.objects.get(user_id=request.user.id)
    message=None
    mydict={'appointmentForm':appointmentForm,'patient':patient,'message':message}

    if request.method=='POST':
        appointmentForm=PatientAppointmentForm(request.POST)

        if appointmentForm.is_valid():

            description=request.POST.get('description')
            doctor=Doctor.objects.get(user_id=request.POST.get('doctorId'))
            appointment=appointmentForm.save(commit=False)
            appointment.doctorId=request.POST.get('doctorId')
            appointment.patientId=request.user.id #----user can choose any patient but only their info will be stored
            appointment.doctorName=User.objects.get(id=request.POST.get('doctorId'))
            appointment.patientName=patient.get_name
            patient.assignedDoctorId=appointment.get_docId
            patient.symptoms=appointment.get_description
            appointment.status=False
            patient.save()
            appointment.save()

            return HttpResponseRedirect(reverse('MyApp:patient_my_appointment'))
        else:
                print(appointmentForm.errors)

    else: #no POST yet
        appointmentForm = PatientAppointmentForm()
    return render(request,'MyApp/patient_book_appointment.html',context=mydict)

@login_required
def patient_my_appointment(request):
    patient=Patient.objects.get(user_id=request.user.id)
    appointments=Appointment.objects.all().filter(patientId=request.user.id)
    return render (request, 'MyApp/patient_my_appointment.html', {'appointments':appointments,'patient':patient})

@login_required
def wait_approval(request):
    return render (request, 'MyApp/wait_approval.html')

def PatientSignUp(request):
    registered = False

    if request.method == "POST":
        user_form = PatientUserInfo(data=request.POST)
        patient_form = PatientSignUpForm(data=request.POST)

        if user_form.is_valid() and patient_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            patientForm = patient_form.save(commit=False)
            patientForm.user = user
            patientForm.save()
            my_patient_group = Group.objects.get_or_create(name='PATIENT')
            my_patient_group[0].user_set.add(user)
            registered=True
            return redirect('MyApp:patientlogin')

        else:
                print(user_form.errors, patient_form.errors)

    else: #no POST yet
        user_form = PatientUserInfo()
        patient_form = PatientSignUpForm()

    return render(request, "MyApp/patientsignup.html",
        {'user_form':user_form, 'patient_form': patient_form,'registered':registered})

def PatientLogin(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password=password)

        if user:
            if user.is_active:
                login(request, user) #login is the django's default function

                return HttpResponseRedirect(reverse('MyApp:afterlogin_view'))

            else:
                return HttpResponse("Account not Active")

        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid Login details supplied!")

    else:
        return render(request, 'MyApp/patientlogin.html',{})

#------------------------ DOCTOR RELATED VIEWS START ------------------------------
#-----------------------------------------------------------------------------------


@login_required
def doctor_dashboard(request):
    doctor=Doctor.objects.get(user_id=request.user.id)
    patientcount=Patient.objects.all().filter(status=True,assignedDoctorId=request.user.id).count()
    appointmentcount=Appointment.objects.all().filter(status=True,doctorId=request.user.id).count()
    patientdischarged=PatientDischarge.objects.all().distinct().filter(assignedDoctorName=doctor.get_name).count()
    mydict={
    'patientcount':patientcount,
    'appointmentcount':appointmentcount,
    'patientdischarged':patientdischarged,
    }
    return render (request, 'MyApp/doctor_dashboard.html',context=mydict)

@login_required
def doctor_wait_approval(request):
    return render (request, 'MyApp/doctor_wait_approval.html')

@login_required
def doctor_patient(request):
    mydict={
    'doctor':Doctor.objects.get(user_id=request.user.id),
    }
    return render(request,'MyApp/doctor_patient.html',context=mydict)

@login_required
def doctor_view_patient(request):
    patients=Patient.objects.all().filter(status=True, assignedDoctorId=request.user.id)
    doctor=Doctor.objects.get(user_id=request.user.id)
    return render(request,'MyApp/doctor_view_patient.html',{'patients':patients,'doctor':doctor})

@login_required
def doctor_view_discharged_patient(request):
    doctor=Doctor.objects.get(user_id=request.user.id)
    dischargedpatients=PatientDischarge.objects.all().distinct().filter(assignedDoctorName=doctor.get_name)
    return render(request,'MyApp/doctor_view_discharged_patient.html',{'dischargedpatients':dischargedpatients,'doctor':doctor})


@login_required
def doctor_appointment(request):
    return render (request, 'MyApp/doctor_appointment.html')

@login_required
def doctor_view_appointment(request):
    doctor=Doctor.objects.get(user_id=request.user.id)

templates/MyApp/adminlogin.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang= "en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device=width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{%  static 'css/loginform.css' %}"/> 
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> 
        <title>Admin Login · Ask A Doctor</title>
             
    </head>
    <body >
        <div class="container" style="align-items:center">
            <div class="name">  
            </div>
            <div class="content-box">
                <div class="content-main">
                    <div class="login-form">
                        <h1>Admin Login</h1>
                        <h4>New Admin? <a href="{% url 'MyApp:adminsignup' %}">Register Here!</a></h4><br>
                         <form action="{% url 'MyApp:adminlogin' %}" method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <label for="username">Username:</label>
                            <input type="username" name="username" placeholder="Enter Username">
                            <br><br>
                            <label for="password">Password:</label>
                            <input type="password" name="password"><br>
                        <input type="submit" class="btn-primary" value="Log in">
                        </form>
                    </div>
                    
                </div>
            </div>
       </div>
    </body>   
    <style> 
                body  
                {  
                    background-image:url("https://styledme.com/wp-content/uploads/2021/03/minimal-zoom-background.jpg"); 
                    background-repeat: no-repeat; 
                    max_width=100%;
                    max_height=100%;
                    background-size: cover;
                    position: relative;
                } 
            
    </style>  
</html>
            

templates/MyApp/doctor_dashboard.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Doctor · Home</title>
</head>
<body>  
    {% include 'MyApp/doctor_base.html' %}
    {% include 'MyApp/doctor_dashboard_card.html' %}
    
</body>
</html>

templates/MyApp/home_book_appointment.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang= "en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device=width, initial-scale=1.0"> 
        <link rel="stylesheet" href="{%  static 'css/homestyle.css' %}"/>  
        <title>Home · Ask A Doctor</title>
             
    </head>
    <body>
            <div class="container" style="font-family: serif" >
                {% include 'MyApp/web_head.html' %}
                {% include 'MyApp/navbar.html' %}
        
            <h2 style="margin:30px; text-align:center"><a href="{% url 'MyApp:patientlogin' %}" >Login Here to Book Appointment</a></h2>

        </div>
        </body>
        </html>

templates/MyApp/navbar.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang= "en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device=width, initial-scale=1.0">
        <title>Home</title>

    </head>
    <body>
            <div class="container" style="font-family: serif" >
            <div class="navbar">
                <a href="{% url 'MyApp:home' %}">Home</a>
                    <div class="dropdown">
                        <button class="dropbtn">Patient Care ៴
                        </button>
                        <div class="dropdown-content">
                        <a href="{% url 'MyApp:home_book_appointment' %}">Book an Appointment</a>
                        <a href="{% url 'MyApp:patientlogin' %}">Patient Login</a>
                        </div>
                    </div>
                    <div class="dropdown">
                        <button class="dropbtn">Management ៴
                        </button>
                        <div class="dropdown-content">
                        <a href="{% url 'MyApp:adminlogin' %}">Admin Login</a>
                        <a href="{% url 'MyApp:doctorlogin' %}">Doctor Login</a>
                        </div>
                    </div>
            </div>


    </body>
    <style>
        body {
            background-color: rgb(255, 255, 255);
            padding: 0px;
            margin-top: 0px;
            margin-left: 0px;
            margin-right: 0px;
            margin-bottom: 0px;
        }
        .navbar {
            overflow: hidden;
            background-color: rgb(255, 206, 70);
        }

        .navbar a {
            float: left;
            display:block;
            font-size: 18px;
            color: black;
            text-align: center;
            padding: 18px 16px;
            text-decoration: none;
        }
        .navbar a.right{
            float:right;
        }
        .dropdown {
        float: left;
        overflow: hidden;
        }

        .dropdown .dropbtn {
            font-size: 18px;
            border: none;
            outline: none;
            color: black;
            padding: 16px 16px 12px;
            background-color: inherit;
            font-family: inherit;
            margin: 0;
        }

        .navbar a:hover, .dropdown:hover .dropbtn {
            color: rgb(0, 146, 146);
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            z-index: 1;
        }

        .dropdown-content a {
        float: none;
        color: black;
        padding: 12px 20px;
        text-decoration: none;
        display: block;
        text-align:justify;
        }

        .dropdown-content a:hover {
            background-color: rgb(240, 240, 240);
        }

        .dropdown:hover .dropdown-content {
        display: block;
        }
        .sticky {
            position: fixed;
            top: 0;
            width: 100%;
            }

        .sticky + .content {
            padding-top: 60px;
        }

    </style>
    <script>
        window.onscroll = function() {myFunction()};

        var navbar = getElementsById("navbar");
        var sticky = navbar.offsetTop:

        function myFunction() {
        if (window.pageYOffset >= sticky) {
            navbar.classList.add("sticky");
        } else {
            navbar.classList.remove("sticky");
        }
        }
</script>

</html>

templates/MyApp/patient_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient · Home</title>
</head>
<body>  
   
    <div class="navbar">
        <a>Patient Information</a>
        <a href="{% url 'MyApp:logout' %}" class="logoutbtn">Logout</a>
        
    </div>
     <div class="sidebar">
        <div class="userprofile">
            <h2 style="color:white; font-family:sans-serif; padding-top:30px; text-align:center; margin:0px; font-size:20px;">Welcome!</h2>
            <h4 style="color:white; font-family:sans-serif; text-align:center; padding-bottom:35px;font-size:20px;">{{request.user.username}}</h4>
        </div>
        <a href="{% url 'MyApp:patient_dashboard' %}"><img class="icon" src="{% static "images/PDash.png" %}">Dashboard</a>
        <a href="{% url 'MyApp:patient_book_appointment' %}"><img class="icon" src="{% static "images/ApptIcon.png" %}">Book an Appointment</a>
        <a href="{% url 'MyApp:patient_my_appointment' %}"><img class="icon" src="{% static "images/PApptHist.png" %}">My Appointments</a>
        <a href="{% url 'MyApp:patient_invoice' %}"><img class="icon" src="{% static "images/Invoice.png" %}">Invoice</a>
    </div>
    
<style> 
        body {
            background-color: rgb(255, 255, 255);
            padding: 0px;
            margin-top: 0px;
            margin-left: 0px;
            margin-right: 0px;
            margin-bottom: 0px;
        }
        .navbar {
            overflow: hidden;
            background-color: rgb(255, 206, 70);
            height:75px;
            width:100%;
            padding-top:22px;
            z-index:1;
            top:0;
            position:fixed;
            display:block;
        }
        .navbar a {
            float: left;
            display:block;
            font-size: 20px;
            color: black;
            text-align: center;
            text-decoration: none;
        }
        
        .navbar .logoutbtn{
            float: right;
            display:block;
            font-size: 16px;
            color: black;
            text-align: center;
            padding-bottom:2px;
            text-decoration: none;
        }
        .navbar .logoutbtn:hover{
            color: rgb(0, 146, 146);

        }
        .sidebar .userprofile{
            background-color: rgb(0, 122, 122);
        }
        .sidebar {
            margin-top: 8px;
            padding-top: 0px;
            width: 20%;
            text-align: center;
            height=100%%;
            background-color: rgb(0, 146, 146);
            font-family: sans-serif;
            font-size:17px;
            font-weight: normal;
            position: fixed;
            top: 67px;
            left: 0;
            bottom: 0;
           
        }
        .sidebar a {
            display: block;
            color: white;
            padding: 25px;
            text-decoration: none;
        }
        .icon{
            float:left;
            
            width:30px;
            height:30px;
        }
 
        .sidebar a.active {
            color: rgb(255, 206, 70);
        }

        .sidebar a:hover:not(.active) {
            color: rgb(255, 206, 70);
        }

        @media screen and (max-width: 700px) {
        .sidebar {
            width: 100%;
            height: auto;
            position: relative;
        }
        .sidebar a {float: left;}
            div.content {margin-left: 0;}
        }

        @media screen and (max-width: 400px) {
            .sidebar a {
                text-align: center;
                float: none;
            }
        }
</style>
{%  block content_dashboard %}
{%  endblock content_dashboard %}
</body>
</html>